version: '3.8'

services:
  web:
    build: ./django-airbnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-airbnb_backend/:/usr/src/django_airbnb_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangoairbnb

volumes:
  postgres_data: