version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/django-airbnb_backend/media
  web:
    build: ./django-airbnb_backend
    command: gunicorn django_airbnb_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django-airbnb_backend/:/usr/src/django_airbnb_backend
      - media_volume:/usr/src/django-airbnb_backend/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangoairbnb

volumes:
  postgres_data:
  media_volume: